all:
	gcc valid_pack.c -o valid_pack -lm
	gcc sort.c -o sort
	gcc readTxt.c -o  readTxt
	gcc choose_zero_block.c -o choose_zero_block
	gcc merge_pack.c -o merge_pack -lm
	#gcc jugdeBoundary.c -o jugdeBoundary
	#gcc new_valid_pack.c -o new_valid_pack
clean:
	rm -rf valid_pack
	rm -rf sort
	rm -rf readTxt
	rm -rf choose_zero_block
	rm -rf merge_pack
	#rm -rf jugdeBoundary
	#rm -rf new_valid_pack
